
// Reducers
export const USER_AUTHENTICATED = `USER_AUTHENTICATED`
export const FETCH_USER = `FETCH_USER`
export const SUBSCRIPTION_DETAILS = `SUBSCRIPTION_DETAILS`
export const USER_PROFILE_EDIT = `USER_PROFILE_EDIT`
export const ADD_JOB = `ADD_JOB`
export const DRIVER_PROFILE_EDIT = `DRIVER_PROFILE_EDIT`
export const SUBSCRIPTION_MODAL = `SUBSCRIPTION_MODAL`
export const TRAINING_COMPLETE_MODAL = `TRAINING_COMPLETE_MODAL`
export const PAYMENTVERIFICATION_MODAL = `PAYMENTVERIFICATION_MODAL`